name: DevSecOps Security Pipeline

on:
  push:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install Semgrep
      - name: Install Semgrep
        run: pip install semgrep

      # Install REAL TruffleHog v3
      - name: Install TruffleHog
        run: |
          wget https://github.com/trufflesecurity/trufflehog/releases/latest/download/trufflehog_linux_amd64.tar.gz
          tar -xvzf trufflehog_linux_amd64.tar.gz
          chmod +x trufflehog
          sudo mv trufflehog /usr/local/bin/
          trufflehog --version


      # Secret scan
      - name: Run Secret Scan
        run: trufflehog filesystem . --no-verification

      # SAST scan
      - name: Run SAST Scan
        run: semgrep --config=p/python .
